<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>33d6b29b-be63-449a-8f2d-2a12c0731327</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mediator.SourceGenerator" Version="3.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
        <PackageReference Include="Scriban" Version="7.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Modules\Accounting\Accounting.Api\Accounting.Api\Accounting.Api.csproj" />
      <ProjectReference Include="..\..\Modules\Accounting\Accounting.Application\Accounting.Application\Accounting.Application.csproj" />
      <ProjectReference Include="..\..\Modules\Accounting\Accounting.Infrastructure\Accounting.Infrastructure\Accounting.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Modules\Catalog\Catalog.Api\Catalog.Api\Catalog.Api.csproj" />
      <ProjectReference Include="..\..\Modules\Catalog\Catalog.Application\Catalog.Application\Catalog.Application.csproj" />
      <ProjectReference Include="..\..\Modules\Catalog\Catalog.Infrastructure\Catalog.Infrastructure\Catalog.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Modules\Crm\Crm.Api\Crm.Api\Crm.Api.csproj" />
      <ProjectReference Include="..\..\Modules\Crm\Crm.Application\Crm.Application\Crm.Application.csproj" />
      <ProjectReference Include="..\..\Modules\Crm\Crm.Infrastructure\Crm.Infrastructure\Crm.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Modules\Identity\Identity.Api\Identity.Api\Identity.Api.csproj" />
      <ProjectReference Include="..\..\Modules\Identity\Identity.Infrastructure\Identity.Infrastructure\Identity.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Modules\Reference\Reference.Api\Reference.Api\Reference.Api.csproj" />
      <ProjectReference Include="..\..\Modules\Reference\Reference.Application\Reference.Application\Reference.Application.csproj" />
      <ProjectReference Include="..\..\Modules\Reference\Reference.Infrastructure\Reference.Infrastructure\Reference.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Host.Api\obj\**" />
      <Compile Remove="Host.Api\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Host.Api\obj\**" />
      <EmbeddedResource Remove="Host.Api\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="Host.Api\obj\**" />
      <Content Remove="Host.Api\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Host.Api\obj\**" />
      <None Remove="Host.Api\**" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Host.Api\obj\Host.Api.csproj.nuget.dgspec.json" />
      <_ContentIncludedByDefault Remove="Host.Api\obj\project.assets.json" />
    </ItemGroup>

</Project>
