// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reference.Infrastructure.DataBase;

#nullable disable

namespace Reference.Infrastructure.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    [Migration("20260619122000_FixProductCategoryPathType")]
    partial class FixProductCategoryPathType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        }
    }
}
