<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
</PropertyGroup>

    <ItemGroup>
      <Content Include="Seeders\ProductCategories\Data\product_category.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Catalog.Application\Catalog.Application\Catalog.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Slugify.Core" Version="5.1.1" />
      <PackageReference Include="TranslitKit" Version="1.0.3" />
    </ItemGroup>

</Project>
