// <auto-generated />
using System;
using System.Collections.Generic;
using Catalog.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260930102028_GenerateMediaFileIdInDatabase")]
    partial class GenerateMediaFileIdInDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Media.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("MediaFiles", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.ProductCategories.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)");

                    b.Property<string>("RuName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path");

                    b.HasIndex("IsActive", "SortOrder");

                    b.HasIndex("ParentId", "Slug")
                        .IsUnique();

                    b.ToTable("ProductCategories", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.PpeProductDetails", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RetailPercent", "Catalog.Domain.Products.Entities.PpeProductDetails.RetailPercent#RetailPricePercent", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("AdditionalReferenceId")
                                .HasColumnType("integer")
                                .HasColumnName("RetailAdditionalReferenceId");

                            b1.Property<decimal?>("CustomPercent")
                                .HasColumnType("numeric")
                                .HasColumnName("RetailCustomPercent");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RetailPercentSource");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WholesalePercent", "Catalog.Domain.Products.Entities.PpeProductDetails.WholesalePercent#WholesalePricePercent", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("AdditionalReferenceId")
                                .HasColumnType("integer")
                                .HasColumnName("WholesaleAdditionalReferenceId");

                            b1.Property<decimal?>("CustomPercent")
                                .HasColumnType("numeric")
                                .HasColumnName("WholesaleCustomPercent");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("WholesalePercentSource");
                        });

                    b.HasKey("ProductId");

                    b.ToTable("PpeProductDetails", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DescriptionRu")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("DescriptionUk")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RuName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RuName")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductAccessory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("GarmentAccessoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "GarmentAccessoryId");

                    b.ToTable("SewingProductAccessories", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductCategoryReference", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.HasKey("ProductId", "Id");

                    b.HasIndex("Id");

                    b.ToTable("ProductCategoryLinks", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductCharacteristicRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LabelRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LabelUk")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueRu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ValueUk")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("ProductCharacteristicRows", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductCharacteristicTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleUk")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCharacteristicTables", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductFabric", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("FabricId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "FabricId");

                    b.ToTable("SewingProductFabrics", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductInformationBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TextRu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TextUk")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleUk")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInformationBlocks", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductOperation", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("GarmentPartOperationId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "GarmentPartOperationId");

                    b.ToTable("SewingProductOperations", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductPhoto", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Alt")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "Id");

                    b.HasIndex("ProductId", "MediaFileId")
                        .IsUnique();

                    b.ToTable("ProductPhotos", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.SewingProductDetails", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MetersPerProduct")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.ToTable("SewingProductDetails", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.ProductCategories.Entities.ProductCategory", b =>
                {
                    b.HasOne("Catalog.Domain.ProductCategories.Entities.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.PpeProductDetails", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Entities.Product", null)
                        .WithOne("PpeDetails")
                        .HasForeignKey("Catalog.Domain.Products.Entities.PpeProductDetails", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductAccessory", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Entities.SewingProductDetails", null)
                        .WithMany("Accessories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductCategoryReference", b =>
                {
                    b.HasOne("Catalog.Domain.ProductCategories.Entities.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Catalog.Domain.Products.Entities.Product", null)
                        .WithMany("Categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductCharacteristicRow", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Entities.ProductCharacteristicTable", null)
                        .WithMany("Rows")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductCharacteristicTable", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Entities.Product", null)
                        .WithMany("CharacteristicTables")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductFabric", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Entities.SewingProductDetails", null)
                        .WithMany("Fabrics")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductInformationBlock", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Entities.Product", null)
                        .WithMany("InformationBlocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductOperation", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Entities.SewingProductDetails", null)
                        .WithMany("Operations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductPhoto", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Entities.Product", null)
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.SewingProductDetails", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Entities.Product", null)
                        .WithOne("SewingDetails")
                        .HasForeignKey("Catalog.Domain.Products.Entities.SewingProductDetails", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.Product", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CharacteristicTables");

                    b.Navigation("InformationBlocks");

                    b.Navigation("Photos");

                    b.Navigation("PpeDetails");

                    b.Navigation("SewingDetails");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.ProductCharacteristicTable", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Entities.SewingProductDetails", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("Fabrics");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
